//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : peppa
	/// Data Source    : localhost
	/// Server Version : 13.00.4224
	/// </summary>
	public partial class PeppaDB : LinqToDB.Data.DataConnection
	{
		/// <summary>
		/// アカウント
		/// </summary>
		public ITable<Account>     Accounts     { get { return this.GetTable<Account>(); } }
		/// <summary>
		/// 住所
		/// </summary>
		public ITable<Address>     Addresses    { get { return this.GetTable<Address>(); } }
		/// <summary>
		/// 住所種別
		/// </summary>
		public ITable<AddressType> AddressTypes { get { return this.GetTable<AddressType>(); } }
		/// <summary>
		/// 連絡先
		/// </summary>
		public ITable<Contact>     Contacts     { get { return this.GetTable<Contact>(); } }
		/// <summary>
		/// 連絡先種別
		/// </summary>
		public ITable<ContactType> ContactTypes { get { return this.GetTable<ContactType>(); } }
		/// <summary>
		/// 職員
		/// </summary>
		public ITable<Staff>       Staffs       { get { return this.GetTable<Staff>(); } }

		public PeppaDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PeppaDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	/// <summary>
	/// アカウント
	/// </summary>
	[Table(Schema="base", Name="Account")]
	public partial class Account
	{
		/// <summary>
		/// ユニークID
		/// </summary>
		[Column("uid"),                                                    PrimaryKey,  Identity] public int       Uid            { get; set; } // int
		/// <summary>
		/// アカウントID
		/// </summary>
		[Column("account_id"),                                             NotNull              ] public int       AccountId      { get; set; } // int
		/// <summary>
		/// 職員番号
		/// </summary>
		[Column("staff_no"),                                                  Nullable          ] public string    StaffNo        { get; set; } // varchar(16)
		/// <summary>
		/// 教員番号
		/// </summary>
		[Column("teacher_no"),                                                Nullable          ] public string    TeacherNo      { get; set; } // varchar(16)
		/// <summary>
		/// 学生番号
		/// </summary>
		[Column("student_no"),                                                Nullable          ] public string    StudentNo      { get; set; } // varchar(16)
		/// <summary>
		/// 除籍生番号
		/// </summary>
		[Column("out_student_no"),                                            Nullable          ] public string    OutStudentNo   { get; set; } // varchar(16)
		/// <summary>
		/// 保護者番号
		/// </summary>
		[Column("parent_no"),                                                 Nullable          ] public string    ParentNo       { get; set; } // varchar(16)
		/// <summary>
		/// 利用者番号
		/// </summary>
		[Column("user_id"),                                                   Nullable          ] public string    UserId         { get; set; } // varchar(16)
		/// <summary>
		/// 認証方式
		/// </summary>
		[Column("auth_method_type"),                                       NotNull              ] public int       AuthMethodType { get; set; } // int
		/// <summary>
		/// 有効フラグ
		/// </summary>
		[Column("is_valid"),                                               NotNull              ] public int       IsValid        { get; set; } // int
		/// <summary>
		/// 作成日時
		/// </summary>
		[Column("created_at"),                                             NotNull              ] public DateTime  CreatedAt      { get; set; } // datetime2(7)
		/// <summary>
		/// 作成者
		/// </summary>
		[Column("created_by"),                                             NotNull              ] public string    CreatedBy      { get; set; } // varchar(16)
		/// <summary>
		/// 更新日時
		/// </summary>
		[Column("modified_at"),                                            NotNull              ] public DateTime  ModifiedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 更新者
		/// </summary>
		[Column("modified_by"),                                            NotNull              ] public string    ModifiedBy     { get; set; } // varchar(16)
		/// <summary>
		/// 削除日時
		/// </summary>
		[Column("removed_at"),                                                Nullable          ] public DateTime? RemovedAt      { get; set; } // datetime2(7)
		/// <summary>
		/// 版
		/// </summary>
		[Column("row_version",      SkipOnInsert=true, SkipOnUpdate=true), NotNull              ] public byte[]    RowVersion     { get; set; } // timestamp

		#region Associations

		/// <summary>
		/// FK_Account_Staff
		/// </summary>
		[Association(ThisKey="StaffNo", OtherKey="StaffNo", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_Account_Staff", BackReferenceName="Accounts")]
		public Staff Staff { get; set; }

		#endregion
	}

	/// <summary>
	/// 住所
	/// </summary>
	[Table(Schema="base", Name="Address")]
	public partial class Address
	{
		/// <summary>
		/// ユニークID
		/// </summary>
		[Column("uid"),                                                   PrimaryKey,  Identity] public int       Uid            { get; set; } // int
		/// <summary>
		/// 職員番号
		/// </summary>
		[Column("staff_no"),                                                 Nullable          ] public string    StaffNo        { get; set; } // varchar(16)
		/// <summary>
		/// 教員番号
		/// </summary>
		[Column("teacher_no"),                                               Nullable          ] public string    TeacherNo      { get; set; } // varchar(16)
		/// <summary>
		/// 学生番号
		/// </summary>
		[Column("student_no"),                                               Nullable          ] public string    StudentNo      { get; set; } // varchar(16)
		/// <summary>
		/// 除籍生番号
		/// </summary>
		[Column("out_student_no"),                                           Nullable          ] public string    OutStudentNo   { get; set; } // varchar(16)
		/// <summary>
		/// 保護者番号
		/// </summary>
		[Column("parent_no"),                                                Nullable          ] public string    ParentNo       { get; set; } // varchar(16)
		/// <summary>
		/// 利用者番号
		/// </summary>
		[Column("user_id"),                                                  Nullable          ] public string    UserId         { get; set; } // varchar(16)
		/// <summary>
		/// 連番
		/// </summary>
		[Column("seq"),                                                   NotNull              ] public int       Seq            { get; set; } // int
		/// <summary>
		/// 住所種別
		/// </summary>
		[Column("address_type_id"),                                       NotNull              ] public int       AddressTypeId  { get; set; } // int
		/// <summary>
		/// 郵便番号
		/// </summary>
		[Column("postal_code"),                                           NotNull              ] public string    PostalCode     { get; set; } // varchar(7)
		/// <summary>
		/// 都道府県
		/// </summary>
		[Column("prefecture_code"),                                       NotNull              ] public int       PrefectureCode { get; set; } // int
		/// <summary>
		/// 住所1
		/// </summary>
		[Column("address1"),                                              NotNull              ] public string    Address1       { get; set; } // nvarchar(32)
		/// <summary>
		/// 住所2
		/// </summary>
		[Column("address2"),                                              NotNull              ] public string    Address2       { get; set; } // nvarchar(32)
		/// <summary>
		/// 住所3
		/// </summary>
		[Column("address3"),                                              NotNull              ] public string    Address3       { get; set; } // nvarchar(32)
		/// <summary>
		/// 緯度
		/// </summary>
		[Column("latitude"),                                                 Nullable          ] public decimal?  Latitude       { get; set; } // numeric(11, 8)
		/// <summary>
		/// 経度
		/// </summary>
		[Column("longitude"),                                                Nullable          ] public decimal?  Longitude      { get; set; } // numeric(11, 8)
		/// <summary>
		/// 転入日
		/// </summary>
		[Column("enter_date"),                                               Nullable          ] public DateTime? EnterDate      { get; set; } // datetime2(7)
		/// <summary>
		/// 転出日
		/// </summary>
		[Column("leave_date"),                                               Nullable          ] public DateTime? LeaveDate      { get; set; } // datetime2(7)
		/// <summary>
		/// 作成日時
		/// </summary>
		[Column("created_at"),                                            NotNull              ] public DateTime  CreatedAt      { get; set; } // datetime2(7)
		/// <summary>
		/// 作成者
		/// </summary>
		[Column("created_by"),                                            NotNull              ] public string    CreatedBy      { get; set; } // varchar(16)
		/// <summary>
		/// 更新日時
		/// </summary>
		[Column("modified_at"),                                           NotNull              ] public DateTime  ModifiedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 更新者
		/// </summary>
		[Column("modified_by"),                                           NotNull              ] public string    ModifiedBy     { get; set; } // varchar(16)
		/// <summary>
		/// 削除日時
		/// </summary>
		[Column("removed_at"),                                               Nullable          ] public DateTime? RemovedAt      { get; set; } // datetime2(7)
		/// <summary>
		/// 版
		/// </summary>
		[Column("row_version",     SkipOnInsert=true, SkipOnUpdate=true), NotNull              ] public byte[]    RowVersion     { get; set; } // timestamp

		#region Associations

		/// <summary>
		/// FK_Address_AddressType
		/// </summary>
		[Association(ThisKey="AddressTypeId", OtherKey="AddressTypeId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Address_AddressType", BackReferenceName="Addresses")]
		public AddressType AddressType { get; set; }

		/// <summary>
		/// FK_Address_Staff
		/// </summary>
		[Association(ThisKey="StaffNo", OtherKey="StaffNo", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_Address_Staff", BackReferenceName="Addresses")]
		public Staff Staff { get; set; }

		#endregion
	}

	/// <summary>
	/// 住所種別
	/// </summary>
	[Table(Schema="base", Name="AddressType")]
	public partial class AddressType
	{
		/// <summary>
		/// ユニークID
		/// </summary>
		[Column("uid"),                                                   PrimaryKey,  Identity] public int       Uid           { get; set; } // int
		/// <summary>
		/// 住所種別ID
		/// </summary>
		[Column("address_type_id"),                                       NotNull              ] public int       AddressTypeId { get; set; } // int
		/// <summary>
		/// 名称
		/// </summary>
		[Column("name"),                                                  NotNull              ] public string    Name          { get; set; } // nvarchar(10)
		/// <summary>
		/// 説明
		/// </summary>
		[Column("description"),                                           NotNull              ] public string    Description   { get; set; } // nvarchar(64)
		/// <summary>
		/// 表示順
		/// </summary>
		[Column("display_order"),                                         NotNull              ] public int       DisplayOrder  { get; set; } // int
		/// <summary>
		/// 作成日時
		/// </summary>
		[Column("created_at"),                                            NotNull              ] public DateTime  CreatedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 作成者
		/// </summary>
		[Column("created_by"),                                            NotNull              ] public string    CreatedBy     { get; set; } // varchar(16)
		/// <summary>
		/// 更新日時
		/// </summary>
		[Column("modified_at"),                                           NotNull              ] public DateTime  ModifiedAt    { get; set; } // datetime2(7)
		/// <summary>
		/// 更新者
		/// </summary>
		[Column("modified_by"),                                           NotNull              ] public string    ModifiedBy    { get; set; } // varchar(16)
		/// <summary>
		/// 削除日時
		/// </summary>
		[Column("removed_at"),                                               Nullable          ] public DateTime? RemovedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 版
		/// </summary>
		[Column("row_version",     SkipOnInsert=true, SkipOnUpdate=true), NotNull              ] public byte[]    RowVersion    { get; set; } // timestamp

		#region Associations

		/// <summary>
		/// FK_Address_AddressType_BackReference
		/// </summary>
		[Association(ThisKey="AddressTypeId", OtherKey="AddressTypeId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Address> Addresses { get; set; }

		#endregion
	}

	/// <summary>
	/// 連絡先
	/// </summary>
	[Table(Schema="base", Name="Contact")]
	public partial class Contact
	{
		/// <summary>
		/// ユニークID
		/// </summary>
		[Column("uid"),                                                   PrimaryKey,  Identity] public int       Uid            { get; set; } // int
		/// <summary>
		/// 職員番号
		/// </summary>
		[Column("staff_no"),                                                 Nullable          ] public string    StaffNo        { get; set; } // varchar(16)
		/// <summary>
		/// 教員番号
		/// </summary>
		[Column("teacher_no"),                                               Nullable          ] public string    TeacherNo      { get; set; } // varchar(16)
		/// <summary>
		/// 学生番号
		/// </summary>
		[Column("student_no"),                                               Nullable          ] public string    StudentNo      { get; set; } // varchar(16)
		/// <summary>
		/// 除籍生番号
		/// </summary>
		[Column("out_student_no"),                                           Nullable          ] public string    OutStudentNo   { get; set; } // varchar(16)
		/// <summary>
		/// 保護者番号
		/// </summary>
		[Column("parent_no"),                                                Nullable          ] public string    ParentNo       { get; set; } // varchar(16)
		/// <summary>
		/// 利用者番号
		/// </summary>
		[Column("user_id"),                                                  Nullable          ] public string    UserId         { get; set; } // varchar(16)
		/// <summary>
		/// 連番
		/// </summary>
		[Column("seq"),                                                   NotNull              ] public int       Seq            { get; set; } // int
		/// <summary>
		/// 連絡先種別
		/// </summary>
		[Column("contact_type_id"),                                       NotNull              ] public int       ContactTypeId  { get; set; } // int
		/// <summary>
		/// 連絡先
		/// </summary>
		[Column("contact"),                                               NotNull              ] public string    Contact_Column { get; set; } // nvarchar(20)
		/// <summary>
		/// 備考
		/// </summary>
		[Column("note"),                                                  NotNull              ] public string    Note           { get; set; } // nvarchar(200)
		/// <summary>
		/// 作成日時
		/// </summary>
		[Column("created_at"),                                            NotNull              ] public DateTime  CreatedAt      { get; set; } // datetime2(7)
		/// <summary>
		/// 作成者
		/// </summary>
		[Column("created_by"),                                            NotNull              ] public string    CreatedBy      { get; set; } // varchar(16)
		/// <summary>
		/// 更新日時
		/// </summary>
		[Column("modified_at"),                                           NotNull              ] public DateTime  ModifiedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 更新者
		/// </summary>
		[Column("modified_by"),                                           NotNull              ] public string    ModifiedBy     { get; set; } // varchar(16)
		/// <summary>
		/// 削除日時
		/// </summary>
		[Column("removed_at"),                                               Nullable          ] public DateTime? RemovedAt      { get; set; } // datetime2(7)
		/// <summary>
		/// 版
		/// </summary>
		[Column("row_version",     SkipOnInsert=true, SkipOnUpdate=true), NotNull              ] public byte[]    RowVersion     { get; set; } // timestamp

		#region Associations

		/// <summary>
		/// FK_Contact_ContactType
		/// </summary>
		[Association(ThisKey="ContactTypeId", OtherKey="ContactTypeId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Contact_ContactType", BackReferenceName="Contacts")]
		public ContactType ContactType { get; set; }

		/// <summary>
		/// FK_Contact_Staff
		/// </summary>
		[Association(ThisKey="StaffNo", OtherKey="StaffNo", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_Contact_Staff", BackReferenceName="Contacts")]
		public Staff Staff { get; set; }

		#endregion
	}

	/// <summary>
	/// 連絡先種別
	/// </summary>
	[Table(Schema="base", Name="ContactType")]
	public partial class ContactType
	{
		/// <summary>
		/// ユニークID
		/// </summary>
		[Column("uid"),                                                   PrimaryKey,  Identity] public int       Uid           { get; set; } // int
		/// <summary>
		/// 連絡先種別ID
		/// </summary>
		[Column("contact_type_id"),                                       NotNull              ] public int       ContactTypeId { get; set; } // int
		/// <summary>
		/// 名称
		/// </summary>
		[Column("name"),                                                  NotNull              ] public string    Name          { get; set; } // nvarchar(10)
		/// <summary>
		/// 説明
		/// </summary>
		[Column("description"),                                           NotNull              ] public string    Description   { get; set; } // nvarchar(64)
		/// <summary>
		/// 表示順
		/// </summary>
		[Column("display_order"),                                         NotNull              ] public int       DisplayOrder  { get; set; } // int
		/// <summary>
		/// 作成日時
		/// </summary>
		[Column("created_at"),                                            NotNull              ] public DateTime  CreatedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 作成者
		/// </summary>
		[Column("created_by"),                                            NotNull              ] public string    CreatedBy     { get; set; } // varchar(16)
		/// <summary>
		/// 更新日時
		/// </summary>
		[Column("modified_at"),                                           NotNull              ] public DateTime  ModifiedAt    { get; set; } // datetime2(7)
		/// <summary>
		/// 更新者
		/// </summary>
		[Column("modified_by"),                                           NotNull              ] public string    ModifiedBy    { get; set; } // varchar(16)
		/// <summary>
		/// 削除日時
		/// </summary>
		[Column("removed_at"),                                               Nullable          ] public DateTime? RemovedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 版
		/// </summary>
		[Column("row_version",     SkipOnInsert=true, SkipOnUpdate=true), NotNull              ] public byte[]    RowVersion    { get; set; } // timestamp

		#region Associations

		/// <summary>
		/// FK_Contact_ContactType_BackReference
		/// </summary>
		[Association(ThisKey="ContactTypeId", OtherKey="ContactTypeId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Contact> Contacts { get; set; }

		#endregion
	}

	/// <summary>
	/// 職員
	/// </summary>
	[Table(Schema="base", Name="Staff")]
	public partial class Staff
	{
		/// <summary>
		/// ユニークID
		/// </summary>
		[Column("uid"),                                                   PrimaryKey,  Identity] public int       Uid           { get; set; } // int
		/// <summary>
		/// 職員番号
		/// </summary>
		[Column("staff_no"),                                              NotNull              ] public string    StaffNo       { get; set; } // varchar(16)
		/// <summary>
		/// 氏名
		/// </summary>
		[Column("name"),                                                  NotNull              ] public string    Name          { get; set; } // nvarchar(20)
		/// <summary>
		/// かな氏名
		/// </summary>
		[Column("kana"),                                                  NotNull              ] public string    Kana          { get; set; } // nvarchar(20)
		/// <summary>
		/// 略称
		/// </summary>
		[Column("name_abbrev"),                                           NotNull              ] public string    NameAbbrev    { get; set; } // nvarchar(4)
		/// <summary>
		/// 英字氏名
		/// </summary>
		[Column("name_eng"),                                              NotNull              ] public string    NameEng       { get; set; } // varchar(4)
		/// <summary>
		/// 英字略称
		/// </summary>
		[Column("name_eng_abbrev"),                                       NotNull              ] public string    NameEngAbbrev { get; set; } // varchar(4)
		/// <summary>
		/// 性別
		/// </summary>
		[Column("gender"),                                                   Nullable          ] public int?      Gender        { get; set; } // int
		/// <summary>
		/// 生年月日
		/// </summary>
		[Column("birth_date"),                                               Nullable          ] public DateTime? BirthDate     { get; set; } // datetime2(7)
		/// <summary>
		/// 作成日時
		/// </summary>
		[Column("created_at"),                                            NotNull              ] public DateTime  CreatedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 作成者
		/// </summary>
		[Column("created_by"),                                            NotNull              ] public string    CreatedBy     { get; set; } // varchar(16)
		/// <summary>
		/// 更新日時
		/// </summary>
		[Column("modified_at"),                                           NotNull              ] public DateTime  ModifiedAt    { get; set; } // datetime2(7)
		/// <summary>
		/// 更新者
		/// </summary>
		[Column("modified_by"),                                           NotNull              ] public string    ModifiedBy    { get; set; } // varchar(16)
		/// <summary>
		/// 削除日時
		/// </summary>
		[Column("removed_at"),                                               Nullable          ] public DateTime? RemovedAt     { get; set; } // datetime2(7)
		/// <summary>
		/// 版
		/// </summary>
		[Column("row_version",     SkipOnInsert=true, SkipOnUpdate=true), NotNull              ] public byte[]    RowVersion    { get; set; } // timestamp

		#region Associations

		/// <summary>
		/// FK_Account_Staff_BackReference
		/// </summary>
		[Association(ThisKey="StaffNo", OtherKey="StaffNo", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Account> Accounts { get; set; }

		/// <summary>
		/// FK_Address_Staff_BackReference
		/// </summary>
		[Association(ThisKey="StaffNo", OtherKey="StaffNo", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Address> Addresses { get; set; }

		/// <summary>
		/// FK_Contact_Staff_BackReference
		/// </summary>
		[Association(ThisKey="StaffNo", OtherKey="StaffNo", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Contact> Contacts { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Account Find(this ITable<Account> table, int Uid)
		{
			return table.FirstOrDefault(t =>
				t.Uid == Uid);
		}

		public static Address Find(this ITable<Address> table, int Uid)
		{
			return table.FirstOrDefault(t =>
				t.Uid == Uid);
		}

		public static AddressType Find(this ITable<AddressType> table, int Uid)
		{
			return table.FirstOrDefault(t =>
				t.Uid == Uid);
		}

		public static Contact Find(this ITable<Contact> table, int Uid)
		{
			return table.FirstOrDefault(t =>
				t.Uid == Uid);
		}

		public static ContactType Find(this ITable<ContactType> table, int Uid)
		{
			return table.FirstOrDefault(t =>
				t.Uid == Uid);
		}

		public static Staff Find(this ITable<Staff> table, int Uid)
		{
			return table.FirstOrDefault(t =>
				t.Uid == Uid);
		}
	}
}

#pragma warning restore 1591
